// Overlay design tokens — JavaScript twin of core/overlay_tokens_v1.json.
//
// GENERATED by tools/gen_overlay_tokens.py. Do not hand-edit: edit the JSON and
// regenerate. tests/test_overlay_tokens.py fails if this file drifts from the
// canonical values.
//
// Renderers request a ROLE — token("path.measured").color — never a literal
// colour. The role carries the meaning, and the meaning is what must not drift
// between the animation, the frame stepper, exported video and future TV output.

export const CONTRACT_VERSION = 1;

export const OVERLAY_TOKENS = Object.freeze({
  // Positions the cameras actually observed.
  "path.measured": Object.freeze({ "color": "#ff4fa3", "width": 4, "cap": "round" }),
  // Positions the model inferred. Never drawn in the measured colour.
  "path.predicted": Object.freeze({ "color": "#46aaeb", "width": 4, "cap": "round", "alpha_base": 0.6, "alpha_confidence": 0.4 }),
  // Where observation stops and inference begins. DERIVED from the last measured point, never stored — a stored copy drifts away from the path it labels.
  "path.transition": Object.freeze({ "disc_color": "#0d0f12", "disc_radius": 9, "ring_color": "#ffffff", "ring_radius": 6.5, "core_role": "path.measured", "core_radius": 3 }),
  // A real image-space detection with no calibrated measurement behind it. Outlined, never filled: a fill hides the pixels the umpire is judging.
  "mark.detected": Object.freeze({ "color": "#5ce65a", "width": 2, "fill": "none" }),
  // Assumed geometry, not an observation. Always accompanied by the words 'calibrate to measure'.
  "guide.schematic": Object.freeze({ "color": "#f2b134", "width": 3, "dash": [14, 8] }),
  // Real pitch geometry projected from a calibrated camera (crease, stump line).
  "geometry.reference": Object.freeze({ "color": "#ffffff", "width": 3 }),
  // The system could not look. Neutral grey — never the adverse colour, never the safe colour.
  "state.unobserved": Object.freeze({ "color": "#7d8b99", "width": 3 }),
  // A resolved outcome against the batter.
  "status.adverse": Object.freeze({ "color": "#eb3c3c" }),
  // A resolved outcome in the batter's favour.
  "status.safe": Object.freeze({ "color": "#5ec86e" }),
  // Dark stroke under every overlay line. MANDATORY: measured on real footage, no candidate colour reaches 3:1 luminance contrast against sunlit grass, so the casing carries luminance and the hue carries identity.
  "casing": Object.freeze({ "color": "rgba(0,0,0,0.55)", "width_delta": 3 }),
  // Names a drawn element on the frame.
  "label": Object.freeze({ "size": 12, "weight": 700, "transform": "uppercase", "tracking": "0.08em", "knockout_width": 4, "knockout_color": "rgba(0,0,0,0.7)", "color": "#ffffff" }),
  // Prose that explains a state ('schematic — calibrate to measure'). The only non-uppercase text on a frame, because it is read as a sentence.
  "qualifier": Object.freeze({ "size": 11, "weight": 600, "transform": "none", "color": "#ffffff" }),
  // A calibrated number. Value and unit together, never a bare number. White by default; tinted by outcome only when it resolves the decision.
  "measurement": Object.freeze({ "size": 17, "weight": 800, "numeric": "tabular-nums", "color": "#ffffff" }),
  // Which frame is on screen. Same corner on every review type.
  "frame.counter": Object.freeze({ "size": 13, "weight": 700, "family": "mono", "position": "top-left", "format": "FRAME {index}", "color": "#ffffff" }),
  // The standing three-symbol key (measured / guide / detected). Same corner on every review type, so the vocabulary teaches itself.
  "legend": Object.freeze({ "position": "bottom-left", "entries": ["path.measured", "guide.schematic", "mark.detected"] }),
});

// Unknown roles throw: a typo must not silently fall back to a default colour.
export function token(role) {
  const found = OVERLAY_TOKENS[role];
  if (!found) {
    throw new Error("unknown overlay role: " + role + "; known: " + Object.keys(OVERLAY_TOKENS).join(", "));
  }
  return found;
}

// Every overlay stroke gets a dark casing beneath it. Measured on real match
// footage, no candidate colour reaches 3:1 luminance contrast against sunlit
// grass — the casing carries luminance so the hue can carry identity.
export function casingWidth(role) {
  return token(role).width + token("casing").width_delta;
}
