"""Tests for tools/vs_split_by_delivery.py — the delivery-held-out re-splitter.

The tool exists because Vision Studio's Prepare step splits train/val by FRAME
(near-duplicate frames of one delivery land on both sides, so val metrics
measure memorization). These tests pin the honest behaviour: whole deliveries
only, deterministic, yaml preserved except the repaired ``path:`` line.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))

from vs_split_by_delivery import (  # noqa: E402
    SplitError,
    collect_frames,
    declared_classes,
    group_of,
    run,
    split_groups,
)

YAML_TEMPLATE = """# YOLO dataset configuration
# Generated by Vision Studio - Prepare YOLO Dataset
path: E:/II innigs/CAM A/Vision Studio/Annotations/bowl1_MP4
train: images/train
val: images/val
kpt_shape: [2, 3]
flip_idx: [0, 1]

names:
  0: ball
  1: bat
  4: frontfoot
"""


def make_dataset(root: Path, deliveries: dict[str, int], label_class: int = 4) -> Path:
    """Build a prepared-dataset tree the way Vision Studio lays it out,
    frame-interleaved on purpose: even frames -> train, odd -> val."""
    dataset = root / "bowl1_MP4"
    for split in ("train", "val"):
        (dataset / "images" / split).mkdir(parents=True)
        (dataset / "labels" / split).mkdir(parents=True)
    for delivery, count in deliveries.items():
        for index in range(count):
            split = "train" if index % 2 == 0 else "val"
            stem = f"{delivery}_{index:06d}"
            (dataset / "images" / split / f"{stem}.jpg").write_bytes(b"\xff\xd8fake")
            (dataset / "labels" / split / f"{stem}.txt").write_text(
                f"{label_class} 0.5 0.5 0.1 0.1 0.5 0.5 2 0.6 0.6 2\n", encoding="utf-8"
            )
    (dataset / "dataset.yaml").write_text(YAML_TEMPLATE, encoding="utf-8")
    return dataset


def split_of(dataset: Path, stem_prefix: str) -> set:
    found = set()
    for split in ("train", "val"):
        for image in (dataset / "images" / split).iterdir():
            if image.stem.startswith(stem_prefix):
                found.add(split)
    return found


def test_group_of_strips_one_frame_suffix():
    assert group_of("Delivery001_000007") == "Delivery001"
    assert group_of("bowl1_Delivery014_000039") == "bowl1_Delivery014"
    assert group_of("no_digits_tail_abc") == "no_digits_tail_abc"


def test_whole_deliveries_never_straddle_the_split(tmp_path):
    dataset = make_dataset(tmp_path, {f"Delivery{i:03d}": 10 for i in range(1, 11)})
    run(dataset, val_ratio=0.2, seed=42, dry_run=False)
    for i in range(1, 11):
        sides = split_of(dataset, f"Delivery{i:03d}_")
        assert len(sides) == 1, f"Delivery{i:03d} appears in both splits: {sides}"
    frames = collect_frames(dataset)
    val = [f for f in frames if f["split"] == "val"]
    assert 0 < len(val) < len(frames)
    # ~20% of 100 frames, in whole deliveries of 10
    assert len(val) == 20
    # every image kept its label on the same side
    for frame in frames:
        assert frame["label"].exists(), f"label lost for {frame['image'].stem}"


def test_deterministic_and_idempotent(tmp_path):
    dataset = make_dataset(tmp_path, {f"Delivery{i:03d}": 6 for i in range(1, 6)})
    run(dataset, val_ratio=0.2, seed=7, dry_run=False)
    first = {f["image"].stem: f["split"] for f in collect_frames(dataset)}
    run(dataset, val_ratio=0.2, seed=7, dry_run=False)  # second run: no changes
    second = {f["image"].stem: f["split"] for f in collect_frames(dataset)}
    assert first == second


def test_yaml_path_repaired_but_everything_else_preserved(tmp_path):
    dataset = make_dataset(tmp_path, {"Delivery001": 4, "Delivery002": 4})
    run(dataset, val_ratio=0.25, seed=1, dry_run=False)
    text = (dataset / "dataset.yaml").read_text(encoding="utf-8")
    assert f"path: {dataset.resolve().as_posix()}" in text
    assert "E:/II innigs" not in text
    # pose fields and names survive byte-for-byte
    assert "kpt_shape: [2, 3]" in text
    assert "flip_idx: [0, 1]" in text
    assert "4: frontfoot" in text
    assert "# Generated by Vision Studio" in text


def test_dry_run_touches_nothing(tmp_path):
    dataset = make_dataset(tmp_path, {"Delivery001": 4, "Delivery002": 4})
    before = {f["image"].stem: f["split"] for f in collect_frames(dataset)}
    yaml_before = (dataset / "dataset.yaml").read_text(encoding="utf-8")
    run(dataset, val_ratio=0.25, seed=1, dry_run=True)
    after = {f["image"].stem: f["split"] for f in collect_frames(dataset)}
    assert before == after
    assert (dataset / "dataset.yaml").read_text(encoding="utf-8") == yaml_before


def test_refuses_single_delivery(tmp_path):
    dataset = make_dataset(tmp_path, {"Delivery001": 8})
    with pytest.raises(SplitError, match="at least 2"):
        run(dataset, val_ratio=0.2, seed=42, dry_run=False)


def test_refuses_ungroupable_stems(tmp_path):
    dataset = make_dataset(tmp_path, {"DeliveryA": 1, "DeliveryB": 1, "DeliveryC": 1})
    # one frame per group and stems end in _000000 → groups==frames after strip?
    # No: DeliveryA_000000 → group DeliveryA, 3 groups of 1 frame == 3 frames.
    frames = collect_frames(dataset)
    with pytest.raises(SplitError, match="own group"):
        split_groups(frames, 0.2, 42)


def test_declared_classes_parses_sparse_names(tmp_path):
    dataset = make_dataset(tmp_path, {"Delivery001": 2, "Delivery002": 2})
    classes = declared_classes(dataset / "dataset.yaml")
    assert classes == {0: "ball", 1: "bat", 4: "frontfoot"}


def test_val_never_empty_even_with_tiny_ratio(tmp_path):
    dataset = make_dataset(tmp_path, {"Delivery001": 4, "Delivery002": 4})
    run(dataset, val_ratio=0.01, seed=3, dry_run=False)
    frames = collect_frames(dataset)
    val = [f for f in frames if f["split"] == "val"]
    train = [f for f in frames if f["split"] == "train"]
    assert val and train
