"""Generate the JavaScript overlay-token twin from the canonical JSON.

The JSON in ``core/overlay_tokens_v1.json`` is the single source of truth. This
script writes ``dashboard/electron/renderer/overlay/tokens.js`` from it, and
``tests/test_overlay_tokens.py`` fails if the checked-in JS does not match what
this script would produce. Generation plus a parity test is what makes "one
vocabulary, two languages" true rather than aspirational.

    python tools/gen_overlay_tokens.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "core" / "overlay_tokens_v1.json"
TARGET = ROOT / "dashboard" / "electron" / "renderer" / "overlay" / "tokens.js"

HEADER = """// Overlay design tokens — JavaScript twin of core/overlay_tokens_v1.json.
//
// GENERATED by tools/gen_overlay_tokens.py. Do not hand-edit: edit the JSON and
// regenerate. tests/test_overlay_tokens.py fails if this file drifts from the
// canonical values.
//
// Renderers request a ROLE — token("path.measured").color — never a literal
// colour. The role carries the meaning, and the meaning is what must not drift
// between the animation, the frame stepper, exported video and future TV output.
"""

FOOTER = """
// Unknown roles throw: a typo must not silently fall back to a default colour.
export function token(role) {
  const found = OVERLAY_TOKENS[role];
  if (!found) {
    throw new Error("unknown overlay role: " + role + "; known: " + Object.keys(OVERLAY_TOKENS).join(", "));
  }
  return found;
}

// Every overlay stroke gets a dark casing beneath it. Measured on real match
// footage, no candidate colour reaches 3:1 luminance contrast against sunlit
// grass — the casing carries luminance so the hue can carry identity.
export function casingWidth(role) {
  return token(role).width + token("casing").width_delta;
}
"""


def render() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [HEADER, f"export const CONTRACT_VERSION = {data['contract_version']};", "",
             "export const OVERLAY_TOKENS = Object.freeze({"]
    for name, spec in data["roles"].items():
        means = spec.get("means")
        if means:
            lines.append(f"  // {means}")
        body = ", ".join(f"{json.dumps(k)}: {json.dumps(v)}"
                         for k, v in spec.items() if k != "means")
        lines.append(f"  {json.dumps(name)}: Object.freeze({{ {body} }}),")
    lines.append("});")
    lines.append(FOOTER)
    return "\n".join(lines)


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
